### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/InterCom#102] opened 2017-10-03 17:59 UTC
Zikula 1.5.1
Php 5.6

```
Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE intercom_message_user_details (id INT AUTO_INCREMENT NOT NULL, message INT NOT NULL, label INT DEFAULT NULL, seen DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', replied DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', notified DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', stored DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', deleted DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', extraData LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', user INT DEFAULT NULL, UNIQUE INDEX UNIQ_2499FC3BF396750 (id), INDEX IDX_2499FC3B6BD307F (message), INDEX IDX_2499FC3EA750E8 (label), INDEX IDX_2499FC38D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = innodb': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'stored DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', deleted DATETIME DEFA' at line 1' while executing DDL: CREATE TABLE intercom_message_user_details (id INT AUTO_INCREMENT NOT NULL, message INT NOT NULL, label INT DEFAULT NULL, seen DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', replied DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', notified DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', stored DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', deleted DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', extraData LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', user INT DEFAULT NULL, UNIQUE INDEX UNIQ_2499FC3BF396750 (id), INDEX IDX_2499FC3B6BD307F (message), INDEX IDX_2499FC3EA750E8 (label), INDEX IDX_2499FC38D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = innodb
```
2 tables are created in the database:
intercom_labels
intercom_messages
state of the module is 1.

**Comment by Kaik** [comment] 2017-10-03 19:35
Hmm... I will need to do checks on 1.5.1 will do it tommorow.

**Comment by Kaik** [comment] 2017-10-04 17:23
@Portugao I have tested on 1.5.0 and 1.5.2 and installation ``works for me``. My setup is php7. Could you please let me know what version of DB you have? I think it is php7 or doctrine a version issue I need to setup php 5.6 env to check this. This will take me some time because I'm working on other things as well and I do not want to break current env. 

I have found another issue so 3.0.1 is around the corner this week for sure.

**Comment by Portugao** [comment] 2017-10-04 19:40
db version 5.7.14

**Comment by Kaik** [comment] 2017-11-01 15:24
Ok, I can confirm this error on WAMP 5.6.25 Mysql 5.7.14 I'm working on it.

**Comment by Portugao** [comment] 2017-11-01 15:26
I checked with Zikula 1.5.2 again and I got the same error.
Thx for looking at that.

**Comment by Kaik** [comment] 2017-11-01 16:48
Ok, so I have found the problem and I have fixed it locally so installation works. I have found some more issues - which I want to check before committing so stay tuned I will fix installation today for sure even if other issues will not be fixed today.

**Comment by Kaik** [comment] 2017-11-01 22:47
Ok, this is fixed module should install properly. The problem was that I have used mysql reserved keywords I thought doctrine is handling those but looks like it is not. Funny thing is that MariaDB which I'm using does not have any problem with it while mysql do. Anyway, it is ready for testing - v3 branch - at the moment just install, confirm that this problem is solved.

**Comment by Guite** [comment] 2017-11-02 06:45
@Kaik fyi http://docs.doctrine-project.org/en/latest/reference/basic-mapping.html#quoting-reserved-words

**Comment by Kaik** [comment] 2017-11-02 08:44
@Guite It was my first call when I have found out that reserved words are the reason and it worked but then I have found this http://docs.doctrine-project.org/en/latest/reference/best-practices.html#don-t-use-identifier-quoting so I decided to change column name.

**Comment by Guite** [comment] 2017-11-02 08:47
:+1:

**Comment by Portugao** [comment] 2017-11-02 11:07
Thx. Install works like expected. Will do further tests.

**Comment by Kaik** [comment] 2017-11-02 16:18
Ok, I'm closing this now then since it is solved. Thank you very much for testing!

**Closed by Kaik** 2017-11-02 16:18 UTC
